@startuml
activate AddressEditTextPreference
AddressEditTextPreference->AddressEditTextPreference:onClick():OK
activate AddressEditTextPreference
AddressEditTextPreference->AddressDBHelper:new AddressDBHelper()
activate AddressDBHelper
AddressEditTextPreference->AddressDBHelper:insert_address(String address)
AddressDBHelper->DbContract:AddressEntry.ContactsEntry.COLUMN_ADDRESS
activate DbContract
DbContract->AddressDBHelper:COLUMN_ADDRESS
deactivate DbContract
AddressDBHelper->SQLiteDatabase:getWritableDatabase()
activate SQLiteDatabase
AddressDBHelper->SQLiteDatabase:insert(TABLE_NAME, null, ContentValues)
SQLiteDatabase->AddressDBHelper:true
deactivate SQLiteDatabase
AddressDBHelper->AddressEditTextPreference: true
deactivate AddressDBHelper
hide footbox
@enduml