@startuml
activate MainActivity
MainActivity-->MainActivity:onPause()
MainActivity-->OutgoingCallReceiver:OutgoingCallReceiver()
activate OutgoingCallReceiver
OutgoingCallReceiver-->OutgoingCallReceiver:onReceive()
activate OutgoingCallReceiver
deactivate OutgoingCallReceiver
OutgoingCallReceiver-->OutgoingCallReceiver:checkIfNeedBlocking
activate OutgoingCallReceiver
deactivate OutgoingCallReceiver
OutgoingCallReceiver-->ContactsDbHelper:getAllData_contacts()
activate ContactsDbHelper
ContactsDbHelper-->OutgoingCallReceiver:Cursor data
deactivate ContactsDbHelper
OutgoingCallReceiver-->OutgoingCallReceiver:setResultData(null)
activate OutgoingCallReceiver
deactivate OutgoingCallReceiver
hide footbox
@enduml